// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: internal/proto/gopfkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Salt          []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Verifier      []byte                 `protobuf:"bytes,3,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *RegisterUserRequest) GetVerifier() []byte {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetSaltRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaltRequest) Reset() {
	*x = GetSaltRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaltRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaltRequest) ProtoMessage() {}

func (x *GetSaltRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaltRequest.ProtoReflect.Descriptor instead.
func (*GetSaltRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *GetSaltRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetSaltResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salt          []byte                 `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaltResponse) Reset() {
	*x = GetSaltResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaltResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaltResponse) ProtoMessage() {}

func (x *GetSaltResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaltResponse.ProtoReflect.Descriptor instead.
func (*GetSaltResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *GetSaltResponse) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type LoginRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	VerifierCandidate []byte                 `protobuf:"bytes,2,opt,name=verifier_candidate,json=verifierCandidate,proto3" json:"verifier_candidate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetVerifierCandidate() []byte {
	if x != nil {
		return x.VerifierCandidate
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type AddEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cyphertext    []byte                 `protobuf:"bytes,3,opt,name=cyphertext,proto3" json:"cyphertext,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntryRequest) Reset() {
	*x = AddEntryRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntryRequest) ProtoMessage() {}

func (x *AddEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntryRequest.ProtoReflect.Descriptor instead.
func (*AddEntryRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *AddEntryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddEntryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddEntryRequest) GetCyphertext() []byte {
	if x != nil {
		return x.Cyphertext
	}
	return nil
}

func (x *AddEntryRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type AddEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntryResponse) Reset() {
	*x = AddEntryResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntryResponse) ProtoMessage() {}

func (x *AddEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntryResponse.ProtoReflect.Descriptor instead.
func (*AddEntryResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *AddEntryResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetPresignedPutUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedPutUrlRequest) Reset() {
	*x = GetPresignedPutUrlRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedPutUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedPutUrlRequest) ProtoMessage() {}

func (x *GetPresignedPutUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedPutUrlRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedPutUrlRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{8}
}

type GetPresignedPutUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedPutUrlResponse) Reset() {
	*x = GetPresignedPutUrlResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedPutUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedPutUrlResponse) ProtoMessage() {}

func (x *GetPresignedPutUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedPutUrlResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedPutUrlResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *GetPresignedPutUrlResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetPresignedPutUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetPresignedGetUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedGetUrlRequest) Reset() {
	*x = GetPresignedGetUrlRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedGetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedGetUrlRequest) ProtoMessage() {}

func (x *GetPresignedGetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedGetUrlRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedGetUrlRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *GetPresignedGetUrlRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetPresignedGetUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedGetUrlResponse) Reset() {
	*x = GetPresignedGetUrlResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedGetUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedGetUrlResponse) ProtoMessage() {}

func (x *GetPresignedGetUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedGetUrlResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedGetUrlResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *GetPresignedGetUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_internal_proto_gopfkeeper_proto protoreflect.FileDescriptor

const file_internal_proto_gopfkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/gopfkeeper.proto\x12\x12gophkeeper.service\"a\n" +
	"\x13RegisterUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\x12\x1a\n" +
	"\bverifier\x18\x03 \x01(\fR\bverifier\"2\n" +
	"\x14RegisterUserResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\",\n" +
	"\x0eGetSaltRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"%\n" +
	"\x0fGetSaltResponse\x12\x12\n" +
	"\x04salt\x18\x01 \x01(\fR\x04salt\"Y\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12-\n" +
	"\x12verifier_candidate\x18\x02 \x01(\fR\x11verifierCandidate\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"q\n" +
	"\x0fAddEntryRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"cyphertext\x18\x03 \x01(\fR\n" +
	"cyphertext\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"*\n" +
	"\x10AddEntryResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\x1b\n" +
	"\x19GetPresignedPutUrlRequest\"@\n" +
	"\x1aGetPresignedPutUrlResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"-\n" +
	"\x19GetPresignedGetUrlRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\".\n" +
	"\x1aGetPresignedGetUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xd9\x04\n" +
	"\x11GophKeeperService\x12a\n" +
	"\fRegisterUser\x12'.gophkeeper.service.RegisterUserRequest\x1a(.gophkeeper.service.RegisterUserResponse\x12R\n" +
	"\aGetSalt\x12\".gophkeeper.service.GetSaltRequest\x1a#.gophkeeper.service.GetSaltResponse\x12L\n" +
	"\x05Login\x12 .gophkeeper.service.LoginRequest\x1a!.gophkeeper.service.LoginResponse\x12U\n" +
	"\bAddEntry\x12#.gophkeeper.service.AddEntryRequest\x1a$.gophkeeper.service.AddEntryResponse\x12s\n" +
	"\x12GetPresignedPutUrl\x12-.gophkeeper.service.GetPresignedPutUrlRequest\x1a..gophkeeper.service.GetPresignedPutUrlResponse\x12s\n" +
	"\x12GetPresignedGetUrl\x12-.gophkeeper.service.GetPresignedGetUrlRequest\x1a..gophkeeper.service.GetPresignedGetUrlResponseB8Z6github.com/dmitrijs2005/gophkeeper/internal/grpc/protob\x06proto3"

var (
	file_internal_proto_gopfkeeper_proto_rawDescOnce sync.Once
	file_internal_proto_gopfkeeper_proto_rawDescData []byte
)

func file_internal_proto_gopfkeeper_proto_rawDescGZIP() []byte {
	file_internal_proto_gopfkeeper_proto_rawDescOnce.Do(func() {
		file_internal_proto_gopfkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gopfkeeper_proto_rawDesc), len(file_internal_proto_gopfkeeper_proto_rawDesc)))
	})
	return file_internal_proto_gopfkeeper_proto_rawDescData
}

var file_internal_proto_gopfkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_gopfkeeper_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),        // 0: gophkeeper.service.RegisterUserRequest
	(*RegisterUserResponse)(nil),       // 1: gophkeeper.service.RegisterUserResponse
	(*GetSaltRequest)(nil),             // 2: gophkeeper.service.GetSaltRequest
	(*GetSaltResponse)(nil),            // 3: gophkeeper.service.GetSaltResponse
	(*LoginRequest)(nil),               // 4: gophkeeper.service.LoginRequest
	(*LoginResponse)(nil),              // 5: gophkeeper.service.LoginResponse
	(*AddEntryRequest)(nil),            // 6: gophkeeper.service.AddEntryRequest
	(*AddEntryResponse)(nil),           // 7: gophkeeper.service.AddEntryResponse
	(*GetPresignedPutUrlRequest)(nil),  // 8: gophkeeper.service.GetPresignedPutUrlRequest
	(*GetPresignedPutUrlResponse)(nil), // 9: gophkeeper.service.GetPresignedPutUrlResponse
	(*GetPresignedGetUrlRequest)(nil),  // 10: gophkeeper.service.GetPresignedGetUrlRequest
	(*GetPresignedGetUrlResponse)(nil), // 11: gophkeeper.service.GetPresignedGetUrlResponse
}
var file_internal_proto_gopfkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.service.GophKeeperService.RegisterUser:input_type -> gophkeeper.service.RegisterUserRequest
	2,  // 1: gophkeeper.service.GophKeeperService.GetSalt:input_type -> gophkeeper.service.GetSaltRequest
	4,  // 2: gophkeeper.service.GophKeeperService.Login:input_type -> gophkeeper.service.LoginRequest
	6,  // 3: gophkeeper.service.GophKeeperService.AddEntry:input_type -> gophkeeper.service.AddEntryRequest
	8,  // 4: gophkeeper.service.GophKeeperService.GetPresignedPutUrl:input_type -> gophkeeper.service.GetPresignedPutUrlRequest
	10, // 5: gophkeeper.service.GophKeeperService.GetPresignedGetUrl:input_type -> gophkeeper.service.GetPresignedGetUrlRequest
	1,  // 6: gophkeeper.service.GophKeeperService.RegisterUser:output_type -> gophkeeper.service.RegisterUserResponse
	3,  // 7: gophkeeper.service.GophKeeperService.GetSalt:output_type -> gophkeeper.service.GetSaltResponse
	5,  // 8: gophkeeper.service.GophKeeperService.Login:output_type -> gophkeeper.service.LoginResponse
	7,  // 9: gophkeeper.service.GophKeeperService.AddEntry:output_type -> gophkeeper.service.AddEntryResponse
	9,  // 10: gophkeeper.service.GophKeeperService.GetPresignedPutUrl:output_type -> gophkeeper.service.GetPresignedPutUrlResponse
	11, // 11: gophkeeper.service.GophKeeperService.GetPresignedGetUrl:output_type -> gophkeeper.service.GetPresignedGetUrlResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_gopfkeeper_proto_init() }
func file_internal_proto_gopfkeeper_proto_init() {
	if File_internal_proto_gopfkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gopfkeeper_proto_rawDesc), len(file_internal_proto_gopfkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gopfkeeper_proto_goTypes,
		DependencyIndexes: file_internal_proto_gopfkeeper_proto_depIdxs,
		MessageInfos:      file_internal_proto_gopfkeeper_proto_msgTypes,
	}.Build()
	File_internal_proto_gopfkeeper_proto = out.File
	file_internal_proto_gopfkeeper_proto_goTypes = nil
	file_internal_proto_gopfkeeper_proto_depIdxs = nil
}
