// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: internal/proto/gopfkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Salt          []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Verifier      []byte                 `protobuf:"bytes,3,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *RegisterUserRequest) GetVerifier() []byte {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetSaltRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaltRequest) Reset() {
	*x = GetSaltRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaltRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaltRequest) ProtoMessage() {}

func (x *GetSaltRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaltRequest.ProtoReflect.Descriptor instead.
func (*GetSaltRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *GetSaltRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetSaltResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salt          []byte                 `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaltResponse) Reset() {
	*x = GetSaltResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaltResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaltResponse) ProtoMessage() {}

func (x *GetSaltResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaltResponse.ProtoReflect.Descriptor instead.
func (*GetSaltResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *GetSaltResponse) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type LoginRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	VerifierCandidate []byte                 `protobuf:"bytes,2,opt,name=verifier_candidate,json=verifierCandidate,proto3" json:"verifier_candidate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetVerifierCandidate() []byte {
	if x != nil {
		return x.VerifierCandidate
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{6}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Overview      []byte                 `protobuf:"bytes,3,opt,name=overview,proto3" json:"overview,omitempty"`
	NonceOverview []byte                 `protobuf:"bytes,4,opt,name=nonce_overview,json=nonceOverview,proto3" json:"nonce_overview,omitempty"`
	Details       []byte                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	NonceDetails  []byte                 `protobuf:"bytes,6,opt,name=nonce_details,json=nonceDetails,proto3" json:"nonce_details,omitempty"`
	Deleted       bool                   `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Entry) GetOverview() []byte {
	if x != nil {
		return x.Overview
	}
	return nil
}

func (x *Entry) GetNonceOverview() []byte {
	if x != nil {
		return x.NonceOverview
	}
	return nil
}

func (x *Entry) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Entry) GetNonceDetails() []byte {
	if x != nil {
		return x.NonceDetails
	}
	return nil
}

func (x *Entry) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxVersion    int64                  `protobuf:"varint,1,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *SyncRequest) GetMaxVersion() int64 {
	if x != nil {
		return x.MaxVersion
	}
	return 0
}

func (x *SyncRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GlobalMaxVersion int64                  `protobuf:"varint,1,opt,name=global_max_version,json=globalMaxVersion,proto3" json:"global_max_version,omitempty"`
	ProcessedEntries []*Entry               `protobuf:"bytes,2,rep,name=processed_entries,json=processedEntries,proto3" json:"processed_entries,omitempty"`
	NewEntries       []*Entry               `protobuf:"bytes,3,rep,name=new_entries,json=newEntries,proto3" json:"new_entries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gopfkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gopfkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *SyncResponse) GetGlobalMaxVersion() int64 {
	if x != nil {
		return x.GlobalMaxVersion
	}
	return 0
}

func (x *SyncResponse) GetProcessedEntries() []*Entry {
	if x != nil {
		return x.ProcessedEntries
	}
	return nil
}

func (x *SyncResponse) GetNewEntries() []*Entry {
	if x != nil {
		return x.NewEntries
	}
	return nil
}

var File_internal_proto_gopfkeeper_proto protoreflect.FileDescriptor

const file_internal_proto_gopfkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/gopfkeeper.proto\x12\x12gophkeeper.service\"a\n" +
	"\x13RegisterUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\x12\x1a\n" +
	"\bverifier\x18\x03 \x01(\fR\bverifier\"2\n" +
	"\x14RegisterUserResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\",\n" +
	"\x0eGetSaltRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"%\n" +
	"\x0fGetSaltResponse\x12\x12\n" +
	"\x04salt\x18\x01 \x01(\fR\x04salt\"Y\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12-\n" +
	"\x12verifier_candidate\x18\x02 \x01(\fR\x11verifierCandidate\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xcd\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1a\n" +
	"\boverview\x18\x03 \x01(\fR\boverview\x12%\n" +
	"\x0enonce_overview\x18\x04 \x01(\fR\rnonceOverview\x12\x18\n" +
	"\adetails\x18\x05 \x01(\fR\adetails\x12#\n" +
	"\rnonce_details\x18\x06 \x01(\fR\fnonceDetails\x12\x18\n" +
	"\adeleted\x18\a \x01(\bR\adeleted\"c\n" +
	"\vSyncRequest\x12\x1f\n" +
	"\vmax_version\x18\x01 \x01(\x03R\n" +
	"maxVersion\x123\n" +
	"\aentries\x18\x02 \x03(\v2\x19.gophkeeper.service.EntryR\aentries\"\xc0\x01\n" +
	"\fSyncResponse\x12,\n" +
	"\x12global_max_version\x18\x01 \x01(\x03R\x10globalMaxVersion\x12F\n" +
	"\x11processed_entries\x18\x02 \x03(\v2\x19.gophkeeper.service.EntryR\x10processedEntries\x12:\n" +
	"\vnew_entries\x18\x03 \x03(\v2\x19.gophkeeper.service.EntryR\n" +
	"newEntries2\xae\x03\n" +
	"\x11GophKeeperService\x12a\n" +
	"\fRegisterUser\x12'.gophkeeper.service.RegisterUserRequest\x1a(.gophkeeper.service.RegisterUserResponse\x12R\n" +
	"\aGetSalt\x12\".gophkeeper.service.GetSaltRequest\x1a#.gophkeeper.service.GetSaltResponse\x12L\n" +
	"\x05Login\x12 .gophkeeper.service.LoginRequest\x1a!.gophkeeper.service.LoginResponse\x12I\n" +
	"\x04Ping\x12\x1f.gophkeeper.service.PingRequest\x1a .gophkeeper.service.PingResponse\x12I\n" +
	"\x04Sync\x12\x1f.gophkeeper.service.SyncRequest\x1a .gophkeeper.service.SyncResponseB8Z6github.com/dmitrijs2005/gophkeeper/internal/grpc/protob\x06proto3"

var (
	file_internal_proto_gopfkeeper_proto_rawDescOnce sync.Once
	file_internal_proto_gopfkeeper_proto_rawDescData []byte
)

func file_internal_proto_gopfkeeper_proto_rawDescGZIP() []byte {
	file_internal_proto_gopfkeeper_proto_rawDescOnce.Do(func() {
		file_internal_proto_gopfkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gopfkeeper_proto_rawDesc), len(file_internal_proto_gopfkeeper_proto_rawDesc)))
	})
	return file_internal_proto_gopfkeeper_proto_rawDescData
}

var file_internal_proto_gopfkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_proto_gopfkeeper_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),  // 0: gophkeeper.service.RegisterUserRequest
	(*RegisterUserResponse)(nil), // 1: gophkeeper.service.RegisterUserResponse
	(*GetSaltRequest)(nil),       // 2: gophkeeper.service.GetSaltRequest
	(*GetSaltResponse)(nil),      // 3: gophkeeper.service.GetSaltResponse
	(*LoginRequest)(nil),         // 4: gophkeeper.service.LoginRequest
	(*LoginResponse)(nil),        // 5: gophkeeper.service.LoginResponse
	(*PingRequest)(nil),          // 6: gophkeeper.service.PingRequest
	(*PingResponse)(nil),         // 7: gophkeeper.service.PingResponse
	(*Entry)(nil),                // 8: gophkeeper.service.Entry
	(*SyncRequest)(nil),          // 9: gophkeeper.service.SyncRequest
	(*SyncResponse)(nil),         // 10: gophkeeper.service.SyncResponse
}
var file_internal_proto_gopfkeeper_proto_depIdxs = []int32{
	8,  // 0: gophkeeper.service.SyncRequest.entries:type_name -> gophkeeper.service.Entry
	8,  // 1: gophkeeper.service.SyncResponse.processed_entries:type_name -> gophkeeper.service.Entry
	8,  // 2: gophkeeper.service.SyncResponse.new_entries:type_name -> gophkeeper.service.Entry
	0,  // 3: gophkeeper.service.GophKeeperService.RegisterUser:input_type -> gophkeeper.service.RegisterUserRequest
	2,  // 4: gophkeeper.service.GophKeeperService.GetSalt:input_type -> gophkeeper.service.GetSaltRequest
	4,  // 5: gophkeeper.service.GophKeeperService.Login:input_type -> gophkeeper.service.LoginRequest
	6,  // 6: gophkeeper.service.GophKeeperService.Ping:input_type -> gophkeeper.service.PingRequest
	9,  // 7: gophkeeper.service.GophKeeperService.Sync:input_type -> gophkeeper.service.SyncRequest
	1,  // 8: gophkeeper.service.GophKeeperService.RegisterUser:output_type -> gophkeeper.service.RegisterUserResponse
	3,  // 9: gophkeeper.service.GophKeeperService.GetSalt:output_type -> gophkeeper.service.GetSaltResponse
	5,  // 10: gophkeeper.service.GophKeeperService.Login:output_type -> gophkeeper.service.LoginResponse
	7,  // 11: gophkeeper.service.GophKeeperService.Ping:output_type -> gophkeeper.service.PingResponse
	10, // 12: gophkeeper.service.GophKeeperService.Sync:output_type -> gophkeeper.service.SyncResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_gopfkeeper_proto_init() }
func file_internal_proto_gopfkeeper_proto_init() {
	if File_internal_proto_gopfkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gopfkeeper_proto_rawDesc), len(file_internal_proto_gopfkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gopfkeeper_proto_goTypes,
		DependencyIndexes: file_internal_proto_gopfkeeper_proto_depIdxs,
		MessageInfos:      file_internal_proto_gopfkeeper_proto_msgTypes,
	}.Build()
	File_internal_proto_gopfkeeper_proto = out.File
	file_internal_proto_gopfkeeper_proto_goTypes = nil
	file_internal_proto_gopfkeeper_proto_depIdxs = nil
}
